import type { NextPage } from 'next'
import Head from 'next/head'
import type { GetServerSidePropsContext } from 'next'
import { useRouter } from 'next/router'
import { useAuth } from '../hooks/AuthContext'
import nookies from "nookies"
// firebase imports
import { verifyIdToken } from '../config/firebaseAdmin'
// context
// custom components
import Banner from '../components/signup/Banner'
import StoryCard from '../components/signup/StoryCard'
import FaQ from '../components/signup/FaQ'
import Footer from '../components/shared/Footer'

const SignUp: NextPage = () => {

  return (
    <div className="">
      <Head>
        <title>Netflix India &minus; Watch TV Shows Online, Watch Movies Online</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Banner />
      <StoryCard />
      <FaQ />
      <Footer />
    </div>
  )
}

export default SignUp

export async function getServerSideProps(context: GetServerSidePropsContext) {
  const cookies = nookies.get(context)
  if (Object.keys(cookies).length == 0) {
    return {
      props: {}
    }
  }
  return {
    redirect: {
      permanent: true,
      destination: "/browse",
    },
    props: {}
  }
}

